// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqAe2WCBVdIA3_PC6l8pVNUN-i49ra9k',
    appId: '1:540498827266:web:970c7153e93dc33a03af1b',
    messagingSenderId: '540498827266',
    projectId: 'offer-list-project',
    authDomain: 'offer-list-project.firebaseapp.com',
    storageBucket: 'offer-list-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyWAYCFHI9dDBbE1y1ps4UFEEJqrmKrog',
    appId: '1:540498827266:android:b9ec112a12e8874403af1b',
    messagingSenderId: '540498827266',
    projectId: 'offer-list-project',
    storageBucket: 'offer-list-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRQEq9EqVbwjWYsl2w4Gah-eAoC-y67Ik',
    appId: '1:540498827266:ios:df36d0b37f2ed05b03af1b',
    messagingSenderId: '540498827266',
    projectId: 'offer-list-project',
    storageBucket: 'offer-list-project.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRQEq9EqVbwjWYsl2w4Gah-eAoC-y67Ik',
    appId: '1:540498827266:ios:df36d0b37f2ed05b03af1b',
    messagingSenderId: '540498827266',
    projectId: 'offer-list-project',
    storageBucket: 'offer-list-project.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiqAe2WCBVdIA3_PC6l8pVNUN-i49ra9k',
    appId: '1:540498827266:web:76639330d495420803af1b',
    messagingSenderId: '540498827266',
    projectId: 'offer-list-project',
    authDomain: 'offer-list-project.firebaseapp.com',
    storageBucket: 'offer-list-project.appspot.com',
  );

}